name: fastp
description: Download FASTQ files over FTP and perform adapter/quality trimming with fastp, with retry/resume support and soft failure mode.
keywords:
  - trimming
  - quality control
  - fastq
  - ftp
  - download
  - retry
tools:
  - fastp:
      description: |
        A tool designed to provide fast all-in-one preprocessing for FastQ files. This tool is developed in C++ with multithreading supported to afford high performance.
      documentation: https://github.com/OpenGene/fastp
      doi: 10.1093/bioinformatics/bty560
      licence: ["MIT"]
      identifier: biotools:fastp
  - wget:
      description: |
        GNU Wget is a free utility for non-interactive download of files from the Web, supporting HTTP, HTTPS, and FTP protocols.
      documentation: https://www.gnu.org/software/wget/
      licence: ["GPL-3.0-or-later"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information. Use 'single_end: true' to specify single ended or interleaved FASTQs. Use 'single_end: false' for paired-end reads.
          e.g. [ id:'test', single_end:false ]
    - urls:
        type: string
        description: |
          FTP URL string (single-end/interleaved) or list of two FTP URL strings (paired-end)
          for downloading FASTQ files.
    - adapter_fasta:
        type: file
        description: File in FASTA format containing possible adapters to remove.
        pattern: "*.{fasta,fna,fas,fa}"
        ontologies: []
  - discard_trimmed_pass:
      type: boolean
      description: |
        Specify true to not write any reads that pass trimming thresholds.
        This can be used to use fastp for the output report only.
  - save_trimmed_fail:
      type: boolean
      description: Specify true to save files that failed to pass trimming thresholds
        ending in `*.fail.fastq.gz`
  - save_merged:
      type: boolean
      description: Specify true to save all merged reads to a file ending in `*.merged.fastq.gz`
  - max_retries:
      type: integer
      description: Total number of download+fastp attempts before giving up (default 3)
  - wait_retry:
      type: integer
      description: Seconds to wait between retry attempts (default 10)
  - timeout:
      type: integer
      description: wget connection/read/dns timeout in seconds (default 60)
  - resume:
      type: boolean
      description: Use wget --continue to resume partial downloads (default true)
  - soft_fail:
      type: boolean
      description: |
        If true, return empty output files and exit 0 on failure instead of erroring.
        Allows downstream pipeline handling of failures. (default false)
output:
  reads:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fastp.fastq.gz":
          type: file
          description: The trimmed/modified/unmerged fastq reads
          pattern: "*fastp.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_1930 # FASTQ
            - edam: http://edamontology.org/format_3989 # GZIP format
  json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.json":
          type: file
          description: Results in JSON format
          pattern: "*.json"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  html:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.html":
          type: file
          description: Results in HTML format
          pattern: "*.html"
          ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fastp.log":
          type: file
          description: fastp log file
          pattern: "*.fastp.log"
          ontologies: []
  reads_fail:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.fail.fastq.gz":
          type: file
          description: Reads the failed the preprocessing
          pattern: "*fail.fastq.gz"
          ontologies:
            - edam: http://edamontology.org/format_1930 # FASTQ
            - edam: http://edamontology.org/format_3989 # GZIP format
  reads_merged:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.merged.fastq.gz":
          type: file
          description: Reads that were successfully merged
          pattern: "*.{merged.fastq.gz}"
          ontologies: []
  download_log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.download.log":
          type: file
          description: Log of all download attempts including timestamps and outcomes
          pattern: "*.download.log"
          ontologies: []
  status:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.status":
          type: file
          description: File containing "true" or "false" indicating download+fastp success
          pattern: "*.status"
          ontologies: []
  versions_fastp:
    - - "${task.process}":
          type: string
          description: The name of the process
      - fastp:
          type: string
          description: The name of the tool
      - 'fastp --version 2>&1 | sed -e "s/fastp //g"':
          type: eval
          description: The expression to obtain the version of the tool
  versions_wget:
    - - "${task.process}":
          type: string
          description: The name of the process
      - wget:
          type: string
          description: The name of the tool
      - 'wget --version 2>&1 | head -1 | sed -e "s/GNU Wget //;s/ .*//"':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - fastp:
          type: string
          description: The name of the tool
      - 'fastp --version 2>&1 | sed -e "s/fastp //g"':
          type: eval
          description: The expression to obtain the version of the tool
    - - "${task.process}":
          type: string
          description: The name of the process
      - wget:
          type: string
          description: The name of the tool
      - 'wget --version 2>&1 | head -1 | sed -e "s/GNU Wget //;s/ .*//"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@drpatelh"
  - "@kevinmenden"
  - "@eit-maxlcummins"
maintainers:
  - "@drpatelh"
  - "@kevinmenden"
